import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import localFont from 'next/font/local';
import Footer from "@/components/Footer";

const clashGrotesk = localFont({
  src: [
    { path: '../../public/fonts/ClashGrotesk_Complete/ClashGrotesk-Regular.woff2', weight: '400' },
    { path: '../../public/fonts/ClashGrotesk_Complete/ClashGrotesk-Medium.woff2', weight: '500' },
    { path: '../../public/fonts/ClashGrotesk_Complete/ClashGrotesk-Semibold.woff2', weight: '600' },
    { path: '../../public/fonts/ClashGrotesk_Complete/ClashGrotesk-Bold.woff2', weight: '700' },
  ],
  variable: '--font-clash-grotesk',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Finapt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashGrotesk.variable} font-sans antialiased`}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
